#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -rf ./0/epsilon* ./0/k* ./0/nut* ./0/U ./0/U.*

# ----------------------------------------------------------------- end-of-file
