#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#copy mesh from simpleFoam case
cp -r ../cubicBuilding.simpleFoam/constant/polyMesh/ constant/

for time in $(foamInfoExec -times -case ../cubicBuilding.simpleFoam)
do
	[ "$time" = "0" -o "$time" = constant ] || {
		timeDir=$time
		echo "Copying files U, k, epsilon, nut from directory $timeDir"
		cp -r ../cubicBuilding.simpleFoam/${timeDir}/U.gz 0/U.gz
		cp -r ../cubicBuilding.simpleFoam/${timeDir}/k.gz 0/k.gz
		cp -r ../cubicBuilding.simpleFoam/${timeDir}/epsilon.gz 0/epsilon.gz
		cp -r ../cubicBuilding.simpleFoam/${timeDir}/nut.gz 0/nut.gz
	}
done

echo "Running changeDictionary app..."
changeDictionary > log.changeDictionary

#-- Run on single processor
runApplication `getApplication`

## Run in parallel
## Decompose
#runApplication decomposePar
#
#runParallel `getApplication` 8
#
## Reconstruct
#runApplication reconstructPar -latestTime

# ----------------------------------------------------------------- end-of-file
