#!/bin/sh
cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
cp -r 0.orig 0

## Serial run
runApplication `getApplication`

## Parallel run
#runApplication decomposePar
#runParallel `getApplication` 8
#runApplication reconstructPar -latestTime

