#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

#-- Run on single processor
runApplication `getApplication`

## Run in parallel
## Decompose
#runApplication decomposePar
#
#runParallel `getApplication` 8
#
## Reconstruct
#runApplication reconstructPar -latestTime

# ----------------------------------------------------------------- end-of-file
